version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.12.0
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  test_job:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.17.2
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: make install
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run test
          command: |
            make test
      - store_test_results:
          path: /tmp/test-reports

  build_job:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.17.2
    environment:
      PROJ_NAME: blitzshare.bootstrap.node
      TAG: latest
    steps:
      - checkout
      - kubernetes/install-kubectl
      - aws-cli/setup
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - run:
          name: docker build, tag & push
          command: |
            docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
            docker build -t  ${PROJ_NAME}:${TAG} .
            docker tag ${PROJ_NAME}:${TAG} iamkimchi/${PROJ_NAME}:${TAG}
            docker push iamkimchi/${PROJ_NAME}:${TAG}

  deploy_job:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.17.2
    steps:
      - checkout
      - kubernetes/install-kubectl
      - aws-cli/setup
      - run:
          name: configure cluster context
          command: aws eks --region eu-west-2 update-kubeconfig --name eu-west-2-blitzshare-cluster
      - run:
          name: k8s deploy
          command: |
            make k8s-apply
            kubectl rollout status deployment/blitzshare-bootstrap-dpl -n blitzshare-ns --timeout=120s

workflows:
  test-wf:
    jobs:
      - test_job:
          filters:
            branches:
              ignore:
                - main
  deploy-wf:
    jobs:
      - test_job:
          filters:
            branches:
              only:
                - main
      - build_job:
          context: eu-west-1
          requires:
            - test_job
          filters:
            branches:
              only:
                - main
      - deploy_job:
          context: eu-west-1
          requires:
            - build_job
