apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bootstrap-ns
  name: bootstrap-deployment
  labels:
    app: bootstrap
spec:
  selector:
    matchLabels:
      app: bootstrap
  replicas: 1
  template:
    metadata:
      labels:
        app: bootstrap
    spec:
      containers:
        - name: bootstrap
          image: ${DOCKER_IMAGE_URL}
          imagePullPolicy: Always
          env:
            - name: ENV
              value: ${ENV}
            - name: PORT
              value: "63785"
            - name: QUEUE_URL
              value: kubemq-cluster-grpc.kubemq.svc.cluster.local
          ports:
            - containerPort: 63785
          resources:
            limits:
              memory: 256Mi
              cpu: "250m"
            requests:
              memory: 128Mi
              cpu: "80m"
