apiVersion: v1
kind: Service
metadata:
  labels:
    domain: blitzshare
  name: bootstrap-svc
  namespace: bootstrap-ns
  
spec:
  selector:
    app: bootstrap-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
